### ISSUE TITLE
Redmine 3.4 compatibility

### ISSUE THREAD

**Issue by rompic** [a-ono/redmine_per_project_formatting#13]
Is this plugin compatible to Redmine 3.4?
Thanks for the info!

**Comment by PAStheLoD** [comment]
Based on [this](http://www.redmine.org/projects/redmine/wiki/Changelog_3_4#Text-formatting), it looks like 3.4.* so far hasn't introduced anything incompatible for plugins nor for text formatting itself.

Please try it and report back.
